[tween] fixed #3d-tasks/issues/9430: Automatic pause and resume Node tweens when Node active changes (#17141)
* fixed #3d-tasks/issues/9430: Automatic pause and resume Node tweens when Node active changes

* Fix Tween.clone()

* More unittest for tween.

* Fix comment in action-manager.ts

* Remove unused ActionManager.purgeSharedManager.

* Add more unit test for tween.

* Fix error TS2322: Type 'Tween<T | NonNullable<U>>' is not assignable to type 'Tween<T | U>'. Types of property 'to' are incompatible.

* Add Tween.getTarget()